### ISSUE TITLE
Rate Limiter Queue getting clogged and doesn't finish processing requests

### ISSUE THREAD

**Issue by billygerhard** [twurple/twurple#285]
### Code

If I do it like that, and add them all asynchronously, it just stalls in the queue.

```ts
for(let user of this.users){
      twitchClient.users.getFollowsPaginated({followedUser:user}).getTotalCount()
        .then((followCount)=>{
          userFollowCounts[user.id] = followCount;
          userFollowCountProcessed++;
        });
    }
```

If I do this, they all process

```ts
for(let user of this.users){
      let followCount = await twitchClient.users.getFollowsPaginated({followedUser:user}).getTotalCount();
      userFollowCounts[user.id] = followCount;
      userFollowCountProcessed++;
    }
```

The rate limiter debug shows the proper amount of requests. It processed 20, and had 38 left in the queue, but never finished the 58 requests I put into the queue.
```
[2021-08-17T23:47:25.717Z] 🐞 rate-limiter DEBUG remaining requests: 0
NodeLogger.mjs:99 [2021-08-17T23:47:25.718Z] 🐞 rate-limiter DEBUG doing 1 requests, new queue length is 33
NodeLogger.mjs:99 [2021-08-17T23:47:25.990Z] 🐞 rate-limiter DEBUG remaining requests: 0
NodeLogger.mjs:99 [2021-08-17T23:47:25.991Z] 🐞 rate-limiter DEBUG doing 1 requests, new queue length is 36
NodeLogger.mjs:99 [2021-08-17T23:47:26.230Z] 🐞 rate-limiter DEBUG remaining requests: 0
NodeLogger.mjs:99 [2021-08-17T23:47:26.230Z] 🐞 rate-limiter DEBUG doing 1 requests, new queue length is 38
```

### Expected behavior

If there are still items in the queue, it should always finish processing if/when the rate limits are available for Helix.

### Actual Behavior

After a certain amount of items added to the queue in quick succession, it stalls the queue.

### Environment

Tested in both Node and Browser:

- Version: 5.0.0-pre.15
- Node version: 14
- Browser version: Chrome
- Operating system: Windows 10

**Comment by d-fischer** [comment]
I can't reproduce this, but I think my environment is just to slow to exhibit this behavior.

I updated the `@d-fischer/rate-limiter` package to include some trace logs. Please deep upgrade your project, set the log level to `trace` and post the relevant log statements here.

**Comment by billygerhard** [comment]
I updated the packages, and I am still getting the same thing

There are 58 requests I am trying to process, and it is pulling 17 of them, and 39 are staying in the queue

[2021-09-06T16:12:42.718Z] 🐞 rate-limiter DEBUG Remaining requests: 0
NodeLogger.mjs:99 [2021-09-06T16:12:42.718Z] 🐞 rate-limiter DEBUG Doing 1 requests, new queue length is 33
NodeLogger.mjs:99 [2021-09-06T16:12:42.942Z] 🐞 rate-limiter DEBUG Remaining requests: 0
NodeLogger.mjs:99 [2021-09-06T16:12:42.942Z] 🐞 rate-limiter DEBUG Doing 1 requests, new queue length is 35
NodeLogger.mjs:99 [2021-09-06T16:12:43.171Z] 🐞 rate-limiter DEBUG Remaining requests: 0
NodeLogger.mjs:99 [2021-09-06T16:12:43.172Z] 🐞 rate-limiter DEBUG Doing 1 requests, new queue length is 37
NodeLogger.mjs:99 [2021-09-06T16:12:43.398Z] 🐞 rate-limiter DEBUG Remaining requests: 0
NodeLogger.mjs:99 [2021-09-06T16:12:43.398Z] 🐞 rate-limiter DEBUG Doing 1 requests, new queue length is 39
The function I am running. I have it inside a bigger class, so I took out some shared globals, but it should work. I have my twitch client on a global, not as a parameter like I put below, but makes it easier to reproduce.

async getFollowers(userName:string, twitchClient:ApiClient){
    let users = [];
    let userFollowCounts = {};
    let userFollowCountProcessed = 0;
    const channel:HelixUser = await twitchClient.users.getUserByName(userName);
    let userID = channel.id;
    let request = twitchClient.users.getFollowsPaginated({followedUser:channel});
    let followCount = await request.getTotalCount();
    let follows = await request.getAll();
    let userIds = follows.map(follow=>follow.userId);
    users = await twitchClient.users.getUsersByIds(userIds);
    for(let user of users){
     twitchClient.users.getFollowsPaginated({followedUser:user}).getTotalCount()
        .then((followCount)=>{
          userFollowCounts[user.id] = followCount;
          userFollowCountProcessed++;
        });
    }
  }

**Comment by d-fischer** [comment]
I am aware that nothing was fixed.
As I said, I could not reproduce anything, so I only added trace logs, for which you need to change the log level to `trace`.

**Comment by billygerhard** [comment]
I read `trace` but it didn't actually click in my head to change it off debug.... Here is the stack trace.
[localhost-1630946147205.log](https://github.com/twurple/twurple/files/7117172/localhost-1630946147205.log)

**Comment by d-fischer** [comment]
Please work with me to get this fixed properly as I am still unable to reproduce anything even after understanding where it fails.

- Clone https://github.com/d-fischer/rate-limiter
- Check out the `clogging-fix` branch
- Run `yarn && yarn build && yarn link` in the project
- Run `yarn link @d-fischer/rate-limiter` in your own project
- Repeat your tests
- No matter whether your problem is fixed or not, please send trace logs again.

**Comment by billygerhard** [comment]
This did not fix it. It only ran 1 of the queries, then just stopped. 

[localhost-1631633174094.log](https://github.com/twurple/twurple/files/7163173/localhost-1631633174094.log)

**Comment by d-fischer** [comment]
```
NodeLogger.mjs:99 [2021-09-14T15:24:52.508Z] 🐾 rate-limiter TRACE runNextBatch delayed now:1631633092508 reset:0 delay:-1631633092508
```

Guess I failed at delaying here - this timer probably never runs. Will try fixing it in the next few days.

**Comment by d-fischer** [comment]
Worked around in the latest prereleases (5.2.0-pre.4, commit 81c870a) by switching to a time-based rate limiter.

Will revert that change when Twitch improves their CORS headers.
